spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/daeyeo;
    username: sa
    passward:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
logging:
  level:
    org.hibernate.orm.jdbc.bind: trace #??? ?? 3.x, hibernate6
#    org.hibernate.sql: debug
#    jpa ? hibernate ? ???? sql ? ?? ?? loging ? ??? ?? ???? show_sql? ??? ?? ???
